version: '3'

services:
    backend:
        image: node:alpine
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - ./backend:/home/node/app
        working_dir: /home/node/app
        command: "npm run install-and-start"
        environment:
            PROXY_KEY: Token 584f586d6abf01dfdd15d49f1a2c5838c658e184
            DB_USER: root
            DB_PASSWORD: 5R8W63UE89N55KUT
            DB_HOST: database
            DB_PORT: 27017
            DB_NAME: rbxspin
            JWT_SECRET: 8d02ea7d13e12849a80f38624bf14cb618b8043e2a8b7ceb6c802637f4eeeb05d16d0bd2514832543760c3e262b9e3459a1879eb738d621870230f5e721c6927
        depends_on:
            - database
        logging:
            driver: "json-file"
            options:
                max-size: "10m"

    frontend:
        image: nginx:mainline-alpine
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./nextjs-docker/.next/static:/usr/share/nginx/html
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        working_dir: /home/node/app
        depends_on:
            - backend

    certbot:
        image: certbot/certbot:latest
        volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw

    database:
        image: mongo
        ports:
            - "27017:27017"
        restart: always
        volumes:
            - mongodata:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 5R8W63UE89N55KUT
            MONGO_INITDB_DATABASE: rbxspin

    nextjshost:
        image: nextjs-docker:latest
        volumes:
            - /nextjs-docker
        ports:
            - "3000:3000"
        restart: always
        depends_on:
            - backend

volumes:
    mongodata:
